// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYgyrNnVZp-MMfEuFdwJqcSIG_aLH0uwc',
    appId: '1:205471712399:web:a39ceb4bd6aef35e599cfa',
    messagingSenderId: '205471712399',
    projectId: 'hero-a96df',
    authDomain: 'hero-a96df.firebaseapp.com',
    storageBucket: 'hero-a96df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE1GM9JtvxoSHss1qsfaNeZ2Jo_KWGejY',
    appId: '1:205471712399:android:9b335d244adc661e599cfa',
    messagingSenderId: '205471712399',
    projectId: 'hero-a96df',
    storageBucket: 'hero-a96df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs0zJT3CdbAR4-sPC3rD8RS5HYCPYxFcQ',
    appId: '1:205471712399:ios:6bd6bc7857106957599cfa',
    messagingSenderId: '205471712399',
    projectId: 'hero-a96df',
    storageBucket: 'hero-a96df.appspot.com',
    androidClientId: '205471712399-apln5gjf9naphdubr1juvv1g10kaenj6.apps.googleusercontent.com',
    iosClientId: '205471712399-ngab36mqdr91i16pc8uc462955va3ldv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
